services:
  framegallery:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "7999:7999"
    volumes:
      - ./images:/app/images
      - ./data:/app/data
 #     - ./logs:/app/logs
    env_file: .env