services:
  framegallery:
    # Use pre-built image from GitHub Container Registry
    # Comment out the next line and uncomment 'build' section to build locally
    image: ghcr.io/slknijnenburg/framegallery:latest

    # Build locally (uncomment to use instead of pre-built image)
    # build:
    #   context: .
    #   dockerfile: Dockerfile

    ports:
      - "7999:7999"
    volumes:
      - ${IMAGES_PATH:-./images}:/app/images
      - ${DATA_PATH:-./data}:/app/data
      - ${LOGS_PATH:-./logs}:/app/logs
    env_file: .env
    restart: unless-stopped
