"""Add filters table

Revision ID: 3321dec671a3
Revises: 37a5f869f63c
Create Date: 2025-02-08 16:25:13.724316

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3321dec671a3'
down_revision: Union[str, None] = '37a5f869f63c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('filters',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('query', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('filters', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_filters_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_filters_name'), ['name'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('filters', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_filters_name'))
        batch_op.drop_index(batch_op.f('ix_filters_id'))

    op.drop_table('filters')
    # ### end Alembic commands ###
