"""
Add crop details to image

Revision ID: 72495173e2ef
Revises: 3321dec671a3
Create Date: 2025-05-12 10:59:27.486954

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "72495173e2ef"
down_revision: str | None = "3321dec671a3"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("images", schema=None) as batch_op:
        batch_op.add_column(sa.Column("crop_x", sa.Float(), nullable=True))
        batch_op.add_column(sa.Column("crop_y", sa.Float(), nullable=True))
        batch_op.add_column(sa.Column("crop_width", sa.Float(), nullable=True))
        batch_op.add_column(sa.Column("crop_height", sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("images", schema=None) as batch_op:
        batch_op.drop_column("crop_height")
        batch_op.drop_column("crop_width")
        batch_op.drop_column("crop_y")
        batch_op.drop_column("crop_x")

    # ### end Alembic commands ###
