"""Initial migration

Revision ID: e9e94d88de09
Revises: 
Create Date: 2024-10-30 17:18:02.878801

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e9e94d88de09'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('art_items',
    sa.Column('content_id', sa.String(), nullable=False),
    sa.Column('local_filename', sa.String(), nullable=True),
    sa.Column('category_id', sa.String(), nullable=True),
    sa.Column('slideshow', sa.Boolean(), nullable=True),
    sa.Column('matte_id', sa.String(), nullable=True),
    sa.Column('portrait_matte_id', sa.String(), nullable=True),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('aspect_width', sa.Integer(), nullable=True),
    sa.Column('aspect_height', sa.Integer(), nullable=True),
    sa.Column('image_date', sa.String(), nullable=True),
    sa.Column('content_type', sa.String(), nullable=True),
    sa.Column('thumbnail_filename', sa.String(), nullable=True),
    sa.Column('thumbnail_filetype', sa.String(), nullable=True),
    sa.Column('thumbnail_data', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('content_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('art_items')
    # ### end Alembic commands ###
