name: quality-actions
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Install modules
      working-directory: ./ui
      run: npm install

    - name: Run ESLint
      working-directory: ./ui
      run: npm run lint
